import { __ } from '@wordpress/i18n';
import { useState } from '@wordpress/element';
import {
	useBlockProps,
	InspectorControls,
	BlockControls,
	__experimentalColorGradientSettingsDropdown as ColorGradientSettingsDropdown,
	__experimentalUseMultipleOriginColorsAndGradients as useMultipleOriginColorsAndGradients,
} from '@wordpress/block-editor';
import {
	TextareaControl,
	Placeholder,
	ToolbarGroup,
	ToolbarButton,
	ToggleControl,
	PanelBody,
	SelectControl,
} from '@wordpress/components';
import { parseChordPro } from './chordpro-parser';

/**
 * Editor component for the ChordPro block.
 *
 * Shows a textarea for raw ChordPro input and an optional rendered preview.
 */
export default function Edit( { attributes, setAttributes, clientId } ) {
	const { content, chordColor, showTitle, showArtist, fontFamily } = attributes;
	const blockProps = useBlockProps();
	const colorGradientSettings = useMultipleOriginColorsAndGradients();
	const [ isPreviewMode, setIsPreviewMode ] = useState( false );

	return (
		<div { ...blockProps }>
			<BlockControls>
				<ToolbarGroup>
					<ToolbarButton
						isPressed={ ! isPreviewMode }
						onClick={ () => setIsPreviewMode( false ) }
					>
						{ __( 'ChordPro', 'chordpro-block' ) }
					</ToolbarButton>
					<ToolbarButton
						isPressed={ isPreviewMode }
						onClick={ () => setIsPreviewMode( true ) }
					>
						{ __( 'Preview', 'chordpro-block' ) }
					</ToolbarButton>
				</ToolbarGroup>
			</BlockControls>

			<InspectorControls group="color">
				<ColorGradientSettingsDropdown
					{ ...colorGradientSettings }
					panelId={ clientId }
					settings={ [
						{
							label: __( 'Chords', 'chordpro-block' ),
							colorValue: chordColor,
							onColorChange: ( value ) =>
								setAttributes( {
											   chordColor: value || '',
								} ),
						},
					] }
					__experimentalIsRenderedInSidebar={ true }
				/>
			</InspectorControls>

			   <InspectorControls>
				   <PanelBody
					   title={ __( 'Display', 'chordpro-block' ) }
					   initialOpen={ true }
				   >
					   <ToggleControl
						   label={ __( 'Show song title', 'chordpro-block' ) }
						   help={ __(
							   'Display the title extracted from {title: ...} or {t: ...}.',
							   'chordpro-block'
						   ) }
						   checked={ !! showTitle }
						   onChange={ ( value ) =>
							   setAttributes( { showTitle: value } )
						   }
					   />
					   <ToggleControl
						   label={ __( 'Show song artist', 'chordpro-block' ) }
						   help={ __(
							   'Display the artist extracted from {artist: ...}.',
							   'chordpro-block'
						   ) }
						   checked={ !! showArtist }
						   onChange={ ( value ) =>
							   setAttributes( { showArtist: value } )
						   }
					   />
				   </PanelBody>
			   </InspectorControls>

			   <InspectorControls group="styles">
				   <PanelBody
					   title={ __( 'Styles', 'chordpro-block' ) }
					   initialOpen={ false }
				   >
					   <SelectControl
						   label={ __( 'Font family', 'chordpro-block' ) }
						   value={ fontFamily || 'default' }
						   options={ [
							   {
								   label: __( 'Default (Courier New)', 'chordpro-block' ),
								   value: 'default',
							   },
							   {
								   label: __( 'Roboto Mono', 'chordpro-block' ),
								   value: 'roboto',
							   },
							   {
								   label: __( 'Martian Mono', 'chordpro-block' ),
								   value: 'martian',
							   },
						   ] }
						   onChange={ ( value ) =>
							   setAttributes( { fontFamily: value } )
						   }
					   />
				   </PanelBody>
			   </InspectorControls>

			{ ! isPreviewMode ? (
				<TextareaControl
					className="chordpro-editor__textarea"
					label={ __( 'ChordPro content', 'chordpro-block' ) }
					help={ __(
						'Write your song using ChordPro notation. Place chords inline with [Chord] and use {directive: value} for metadata and section markers.',
						'chordpro-block'
					) }
					value={ content }
					onChange={ ( value ) => setAttributes( { content: value } ) }
					rows={ 12 }
					__nextHasNoMarginBottom={ true }
				/>
			) : content ? (
				<div className="chordpro-editor__preview">
					<div
						className={ [
							'chordpro-song',
							fontFamily === 'roboto' && 'chordpro-font-roboto',
							fontFamily === 'martian' && 'chordpro-font-martian',
						]
							.filter( Boolean )
							.join( ' ' ) }
						style={ {
							'--chordpro-chord-color': chordColor || '#c0392b',
						} }
						// Content is generated by our own parser which escapes all user text.
						// eslint-disable-next-line react/no-danger
						dangerouslySetInnerHTML={ {
							__html: parseChordPro( content, {
								showTitle,
								showArtist,
							} ),
						} }
					/>
				</div>
			) : (
				<Placeholder
					icon="format-audio"
					label={ __( 'ChordPro', 'chordpro-block' ) }
					instructions={ __(
						'Start typing your song in the textarea above using ChordPro notation.',
						'chordpro-block'
					) }
				/>
			) }
		</div>
	);
}
